#!/bin/bash
set -euo pipefail

echo "🔧 Cloudflare Service Fix for FF Node"
echo "====================================="
echo ""

echo "Current situation on FF node:"
echo "- Existing cloudflared service installed"
echo "- Need to configure for SSH tunnel"
echo ""

echo "📋 Steps to execute on FF node (abel@ff):"
echo ""

echo "1️⃣  Check current service status:"
echo "   sudo systemctl status cloudflared"
echo "   cat /etc/cloudflared/config.yml"
echo ""

echo "2️⃣  Option A: Update existing config (Recommended)"
echo "   # Backup current config"
echo "   sudo cp /etc/cloudflared/config.yml /etc/cloudflared/config.yml.backup"
echo ""
echo "   # Copy new SSH tunnel config"
echo "   sudo cp ff_tunnel_config.yaml /etc/cloudflared/config.yml"
echo ""
echo "   # Restart service"
echo "   sudo systemctl restart cloudflared"
echo "   sudo systemctl status cloudflared"
echo ""

echo "3️⃣  Option B: Clean install (if Option A fails)"
echo "   # Uninstall existing service"
echo "   cloudflared service uninstall"
echo ""
echo "   # Remove old config"
echo "   sudo rm -f /etc/cloudflared/config.yml"
echo ""
echo "   # Install with new config"
echo "   cp ff_tunnel_config.yaml ~/.cloudflared/config.yml"
echo "   cloudflared service install"
echo "   sudo systemctl enable cloudflared"
echo "   sudo systemctl start cloudflared"
echo ""

echo "4️⃣  Verify SSH tunnel:"
echo "   # Check tunnel status"
echo "   sudo systemctl status cloudflared"
echo "   sudo journalctl -u cloudflared --since '5 minutes ago'"
echo ""
echo "   # Test SSH access"
echo "   ssh abel@ff.buddhilw.com"
echo ""

echo "⚠️  Notes:"
echo "   - The existing service might be for HTTP tunnels"
echo "   - SSH tunnels use different configuration"
echo "   - Both can coexist with proper ingress rules"
